version: '2.0'

services:
    users-sql-server:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - "1434:1433"
        environment:
            SA_PASSWORD: <YourStrong@Passw0rd>
            ACCEPT_EULA: "Y"
    users-app:
        build: "./RembrandtMScProject/Rembrandt.Users/Rembrandt.Users.Api"
        ports:
            - "5010:5010"
        volumes: 
            - ./users-app:/app
        depends_on: 
            - users-sql-server



