version: '2.0'

services:
    users-sql-server:
        ports:
            - "1434:1433"
    users-app:
        ports:
            - "5002:5002"
    dataset-sql-server:
        ports:
            - "1433:1433"
    dataset-app:
        ports:
            - "5001:5001"
    dataset-stats-app:
        ports:
            - "5003:5003"
    gateway-api:
        ports:
            - "5000:5000"
    